[package]
name = "aws-lambda-cognito-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "httpd"
path = "src/cmd/httpd/main.rs"

[[bin]]
name = "lambda"
path = "src/cmd/lambda/main.rs"

[dependencies]
lambda_http = "0.*"
lambda_runtime = "0.*"
serde = "1"
tokio = { version = "1", features = ["macros"] }
