name: Release

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on: 
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: "🐥 Build"
    runs-on: ubuntu-latest
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-southeast-2
      GLOBAL_PREFIX: alshdavid
      PROJECT_NAME: aws-lambda-cognito-rust
    steps:
      - uses: actions/checkout@v4
      - run: bash .github/scripts/prelude/ubuntu.bash
      - run: bash .github/scripts/prelude/aws.bash
      - run: bash .github/scripts/prelude/just.bash
      - run: bash .github/scripts/prelude/nodejs.bash
      - run: bash .github/scripts/prelude/rust.bash
      - run: bash .github/scripts/prelude/terraform.bash

      - name: "Build"
        run: |
          set -e
          npm install
          just build-publish
          ls -l dist
          ls -l dist/client
          ls -l dist/lambda

      - name: "Deploy"
        run: bash .github/scripts/deploy.bash